title: BloodXtract Team
description: >- # this means to ignore newlines until "baseurl:"
   A team of gamers and friends. Yes, we are filthy casuals.
   
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.bloodxtract.com" # the base hostname & protocol for your site, e.g. https://example.github.io

# Edit these details

home:
  typewrite-text: We play games. And yes, we are filthy casuals.

# syntax highlighter
markdown: kramdown
highlighter: rouge
# permalink: pretty


# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/posts/page/:num/"

collections:
  posts:
    output: true
    permalink: /posts/:year-:month-:day/:title

# Gallery
defaults:
  -
    scope:
      path: "images"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jemoji


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vs/
  - README.md
  - LICENSE
  - .gitignore
  - .ruby-version
  - .buildconfig